spring:
  profiles:
    active: local
  application:
    name: cristock

  datasource:
    url: jdbc:postgresql://localhost:5432/cristock_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

server:
  port: 8080


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}